# Dependencies
markdown:	redcarpet
pygments:	true

# Permalinks
permalink:	/blog/:title

# Setup
title:	 morosaka
tagline:	'Sporting activities support tools'
description:	'Sport and Health iOS apps for Professionals and Enthusiasts.'
url:	http://objectivalia.co
quote: '2014 catalog'

author:
  name:	'Mauro Maria Sacca'
  url:	http://appyouralley.com

paginate:	5

# Custom vars
icon:		/assets/images/icon.png
cover:		/assets/images/cover.jpg

social:
  - icon:	twitter
    url:	https://twitter.com/morosaka
    desc:	Follow me on twitter

  - icon:	github
    url:	https://github.com/morosaka
    desc:	Fork me on github

  - icon:	googleplus-alt
    url:	https://plus.google.com/100211166333568553670
    desc:	Add me on google+

menu:
  - title:	Home
    url:	/

  - title:	About
    url:	/about

copyright:
  author:	morosaka
  url:		http://objectivalia.co
  type_title:	Some rights reserved
  type_url:	http://creativecommons.org/licenses/by-nc/2.5
